# Generated by Django 3.2.5 on 2021-07-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_model',
            fields=[
                ('Product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(max_length=100, null=True)),
                ('Product_Price', models.FloatField()),
                ('Product_Image', models.FileField(upload_to='')),
            ],
        ),
    ]
